/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || 'T3FueElpd292WHlwWGR0QU4xV3pYSmU5VGNlc29kSG5Tb05JMktITWl3QT18YWtxYTEtaXJkY29tcG9zYWIzNWE1LWlyZGNvbXBvc2FiOWY4OS00ZjY5',
config.sitecoreApiHost = process.env.SITECORE_API_HOST || '',
config.jssAppName = process.env.JSS_APP_NAME || 'Guides',
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge',
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en',
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://edge.sitecorecloud.io/api/graphql/v1',
config.sites = process.env.SITES || '[{"name":"Guides","hostName":"*","language":"en"}]',
module.exports = config;